### ISSUE TITLE
browser error  cam / mic

### ISSUE THREAD

**Issue by exiledsurfer** [interspacechat/interspace.chat#11]
can we get this sorted so we work on all browsers? ie BRAVE is a big one.

**Comment by geleeroyale** [comment]
Works for me with Brave, Chrome, Firefox

**Comment by exiledsurfer** [comment]
Ok, changing the brave privacy / security settings for WebRTC to "default public and private interfaces" allows me to access the camera! 

![Screen Shot 2020-03-23 at 12 51 40](https://user-images.githubusercontent.com/1099799/77314099-51088b80-6d05-11ea-9fb6-a8d507e644d0.jpg)

**Comment by geleeroyale** [comment]
Cool you found a fix - closing this.
