### ISSUE TITLE
add donation button

### ISSUE THREAD

**Issue by geleeroyale** [interspacechat/interspace.chat#14]
should link to the gitcoin grants page - https://gitcoin.co/grants/516/interspacechat

**Comment by Deepcryptodive** [comment]
On it!

**Comment by exiledsurfer** [comment]
unfortunately, link opens in same window, closing the interspace, instead of opening in new tab; link should go to: https://gitcoin.co/grants/516/interspacechat?tab=description

**Comment by geleeroyale** [comment]
add direct link to
