### ISSUE TITLE
direct links to rooms do not resolve

### ISSUE THREAD

**Issue by exiledsurfer** [interspacechat/interspace.chat#24]
when clicking on https://noncon.interspace.chat/metatrack from the google calendar , etc, i get a 404 ... shouldnt a link like this open up that room?

**Comment by geleeroyale** [comment]
The room can only be accessed by direct link via the jitsi server - i.e. this address for metatrack https://portal.interspace.chat/metatrack

**Comment by exiledsurfer** [comment]
cool, thx
