### ISSUE TITLE
add google calendar zapier integration

### ISSUE THREAD

**Issue by exiledsurfer** [interspacechat/interspace.chat#6]
https://zapier.com/apps/google-calendar/integrations

**Comment by geleeroyale** [comment]
we don't have a calendar yet, right? can you create one and prepare it for the conference @exiledsurfer ?

not sure we need an integration tho - google calendar has some native stuff too.

**Comment by exiledsurfer** [comment]
i'm in the process of making one; as long as we can embed it in a pop up window, doesn't matter how it happens as far as i'm concerned :-)

**Comment by exiledsurfer** [comment]
have created a calendar for interspace events, here's the embed code @geleeroyale 

<iframe src="https://calendar.google.com/calendar/b/1/embed?height=400&amp;wkst=1&amp;bgcolor=%23e3e9ff&amp;ctz=Europe%2FVienna&amp;src=N3RtbnFxamZtdnB2dGIyNTdycDNlNDkxbmtAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;color=%23F4511E&amp;showPrint=0&amp;showDate=1&amp;mode=AGENDA&amp;showNav=1&amp;showTabs=1&amp;showCalendars=1" style="border-width:0" width="600" height="400" frameborder="0" scrolling="no"></iframe>

**Comment by exiledsurfer** [comment]
@geleeroyale here is the new configured calendar for interspace.chat: 

<iframe src="https://calendar.google.com/calendar/embed?src=7tmnqqjfmvpvtb257rp3e491nk%40group.calendar.google.com&ctz=Europe%2FVienna" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>

**Comment by exiledsurfer** [comment]
ignore above calendar imbed, it was false. here is the correct embed:

<iframe src="https://calendar.google.com/calendar/b/1/embed?height=400&amp;wkst=2&amp;bgcolor=%23ffffff&amp;ctz=Europe%2FVienna&amp;src=N3RtbnFxamZtdnB2dGIyNTdycDNlNDkxbmtAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;src=aWo1cmVzcGM2bHFpN2Y5ZWVkYmcxZWlkbnNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;src=NDgzY3RzbjZkZzIydWp0NW9uczlvOHBmcHNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;src=bDRxbGtzZDgyZDJhZzFia2ljOHB1NDRxbGdAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;color=%23000000&amp;color=%234285F4&amp;color=%238E24AA&amp;color=%23F4511E&amp;mode=AGENDA" style="border:solid 1px #777" width="600" height="400" frameborder="0" scrolling="no"></iframe>

**Comment by exiledsurfer** [comment]
reviewed, is awesome sauce.
